name: Checkout Repository

on:
  workflow_call:
    outputs:
      repo_path:
        value: site-repo

jobs:
  checkout:
    runs-on: ubuntu-latest
    outputs:
      repo_path: site-repo

    steps:
      - name: Checkout Target Repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
          ref: ${{ github.ref_name }}
          path: site-repo

      - name: Debug - Verify Repository and Files
        run: |
          echo "Current Directory: $(pwd)"
          echo "Listing contents of site-repo:"
          ls -la site-repo

      - name: Pass Working Directory
        run: echo "REPO_PATH=site-repo" >> $GITHUB_ENV
