name: Multi-Site Deployment

on:
  push:
    branches:
      - main
  repository_dispatch:

permissions:
  contents: read
  actions: write
  issues: write

jobs:
  detect-project-type:
    runs-on: ubuntu-latest
    outputs:
      project_type: ${{ steps.detect.outputs.PROJECT_TYPE }}

    steps:
      - name: Checkout Project Repo
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.client_payload.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
          ref: main

      - name: Find Next.js Project Directory
        id: find_dir
        run: |
          NEXT_DIR=$(find . -name 'next.config.js' -exec dirname {} \; | head -n 1)
          if [ -z "$NEXT_DIR" ]; then
            echo "❌ next.config.js not found!" && exit 1
          fi
          echo "NEXT_DIR=$NEXT_DIR" >> $GITHUB_ENV
          echo "::set-output name=NEXT_DIR::$NEXT_DIR"

      - name: Debug Repository and Test Files
        run: |
          echo "Current Repository: ${{ github.event.client_payload.repository }}"
          echo "Current Branch: $(git branch --show-current)"
          pwd
          ls -la ${{ env.NEXT_DIR }}
          find ${{ env.NEXT_DIR }} -type f -name "*.test.tsx" -o -name "*.spec.tsx"

      - name: Verify package.json
        run: |
          if [ -f "${{ env.NEXT_DIR }}/package.json" ]; then
            echo "✅ package.json found in ${{ env.NEXT_DIR }}"
          else
            echo "❌ package.json not found in ${{ env.NEXT_DIR }}" && exit 1
          fi

      - name: Read `.cicd-config.yml` (if exists)
        id: detect
        run: |
          PROJECT_TYPE="static"
          if [ -f "${{ env.NEXT_DIR }}/.cicd-config.yml" ]; then
            PROJECT_TYPE=$(grep "project_type:" "${{ env.NEXT_DIR }}/.cicd-config.yml" | awk '{print $2}')
          fi
          if ls ${{ env.NEXT_DIR }}/*.tf 1> /dev/null 2>&1; then
            PROJECT_TYPE="terraform"
          fi
          echo "::set-output name=PROJECT_TYPE::$PROJECT_TYPE"

  static_pipeline:
    needs: detect-project-type
    if: needs.detect-project-type.outputs.project_type == 'static'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Project Repo
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.client_payload.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Find Next.js Project Directory
        id: find_dir
        run: |
          NEXT_DIR=$(find . -name 'next.config.js' -exec dirname {} \; | head -n 1)
          if [ -z "$NEXT_DIR" ]; then
            echo "❌ next.config.js not found!" && exit 1
          fi
          echo "NEXT_DIR=$NEXT_DIR" >> $GITHUB_ENV
          echo "::set-output name=NEXT_DIR::$NEXT_DIR"

      - name: Verify package.json
        run: |
          if [ ! -f "${{ env.NEXT_DIR }}/package.json" ]; then
            echo "❌ package.json not found in ${{ env.NEXT_DIR }}" && exit 1
          fi

      - name: Install Dependencies
        run: |
          cd ${{ env.NEXT_DIR }}
          npm install

      - name: Verify Working Directory and Test Files
        run: |
          cd ${{ env.NEXT_DIR }}
          pwd
          ls -la
          find . -type f -name "*.test.tsx" -o -name "*.spec.tsx"

      - name: Build the Project
        run: |
          cd ${{ env.NEXT_DIR }}
          npm run build

      - name: Run Unit Tests
        run: |
          cd ${{ env.NEXT_DIR }}
          npm test || echo "No tests found, skipping..."

      - name: Deploy to Vercel
        run: |
          cd ${{ env.NEXT_DIR }}
          vercel --prod --token=${{ secrets.VERCEL_TOKEN }}
