name: Multi-Site Deployment

on:
  push:
    branches:
      - main
  repository_dispatch:

permissions:
  contents: read  # ✅ Allows reading repository contents
  actions: write  # ✅ Allows triggering other workflows
  issues: write   # ✅ Allows posting deployment status

jobs:
  detect-project-type:
    runs-on: ubuntu-latest
    outputs:
      project_type: ${{ steps.detect.outputs.PROJECT_TYPE }}

    steps:
      - name: Checkout Project Repo
        uses: actions/checkout@v4
        with:
          repository: awc-create/${{ github.event.repository.name }}
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0  # ✅ Fetches the full repository history
          ref: main       # ✅ Ensures the correct branch is checked out

      - name: Debug Repository Name
        run: echo "Repository Name: ${{ github.event.repository.name }}"

      - name: Verify package.json
        run: |
          if [ -f "package.json" ]; then
            echo "✅ package.json found, proceeding with npm install"
          else
            echo "❌ Error: package.json not found!" && exit 1
          fi

      - name: Read `.cicd-config.yml` (if exists)
        id: detect
        run: |
          PROJECT_TYPE="static"
          if [ -f ".cicd-config.yml" ]; then
            PROJECT_TYPE=$(grep "project_type:" .cicd-config.yml | awk '{print $2}')
          fi

          # Auto-detect Terraform files
          if ls *.tf 1> /dev/null 2>&1; then
            PROJECT_TYPE="terraform"
          fi

          echo "PROJECT_TYPE=$PROJECT_TYPE" >> $GITHUB_ENV
          echo "::set-output name=PROJECT_TYPE::$PROJECT_TYPE"

  static_pipeline:
    needs: detect-project-type
    if: needs.detect-project-type.outputs.project_type == 'static'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Project Repo
        uses: actions/checkout@v4
        with:
          repository: awc-create/${{ github.event.repository.name }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify package.json
        run: |
          if [ -f "package.json" ]; then
            echo "✅ package.json found, proceeding with npm install"
          else
            echo "❌ Error: package.json not found!" && exit 1
          fi

      - name: Install Dependencies
        run: npm install

      - name: Run Unit Tests
        run: npm test

      - name: Build the Project
        run: npm run build

      - name: Deploy to Vercel
        run: vercel --prod --token=${{ secrets.VERCEL_TOKEN }}

  api_pipeline:
    needs: detect-project-type
    if: needs.detect-project-type.outputs.project_type == 'api-heavy'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Project Repo
        uses: actions/checkout@v4
        with:
          repository: awc-create/${{ github.event.repository.name }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify package.json
        run: |
          if [ -f "package.json" ]; then
            echo "✅ package.json found, proceeding with npm install"
          else
            echo "❌ Error: package.json not found!" && exit 1
          fi

      - name: Install Dependencies
        run: npm install

      - name: Run Unit Tests
        run: npm test

      - name: Run Integration Tests
        run: npm run test:integration

      - name: Run End-to-End (E2E) Tests
        uses: cypress-io/github-action@v6
        with:
          start: npm run dev
          wait-on: "http://localhost:3000"

      - name: Build the Project
        run: npm run build

      - name: Deploy to Vercel
        run: vercel --prod --token=${{ secrets.VERCEL_TOKEN }}

  terraform_pipeline:
    needs: detect-project-type
    if: needs.detect-project-type.outputs.project_type == 'terraform'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Project Repo
        uses: actions/checkout@v4
        with:
          repository: awc-create/${{ github.event.repository.name }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify Terraform Configuration
        run: |
          if [ -f "main.tf" ]; then
            echo "✅ Terraform configuration found."
          else
            echo "❌ Error: Terraform files not found!" && exit 1
          fi

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest

      - name: Initialize Terraform
        run: terraform init

      - name: Validate Terraform
        run: terraform validate

      - name: Apply Terraform (Manual Approval Required)
        run: terraform apply -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
