name: Vercel Preview Deployment

on:
  workflow_run:
    workflows: ["Build and Test"]
    types:
      - completed

env:
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  VERCEL_ORG_ID: ${{ secrets[format('{0}_VERCEL_ORG_ID', github.event.workflow_run.head_repository.name)] }}
  VERCEL_PROJECT_ID: ${{ secrets[format('{0}_VERCEL_PROJECT_ID', github.event.workflow_run.head_repository.name)] }}

jobs:
  deploy-preview:
    if: |
      github.event.workflow_run.conclusion == 'success' &&
      (startsWith(github.event.workflow_run.head_branch, 'feat/') ||
       startsWith(github.event.workflow_run.head_branch, 'fix/'))
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Triggering Repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.workflow_run.head_repository.full_name }}
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.event.workflow_run.head_branch }}
          path: site-repo

      - name: Debug - Verify Branch Name
        run: |
          echo "Current branch: ${{ github.event.workflow_run.head_branch }}"
          ls -la
        working-directory: site-repo

      - name: Install Vercel CLI
        run: npm install -g vercel
        working-directory: site-repo

      - name: Pull Vercel Preview Environment
        run: |
          vercel pull --yes \
            --environment=preview \
            --token=${{ env.VERCEL_TOKEN }} \
            --scope=${{ env.VERCEL_ORG_ID }}
        working-directory: site-repo

      - name: Build Project Artifacts
        run: vercel build --token=${{ env.VERCEL_TOKEN }}
        working-directory: site-repo

      - name: Deploy Preview Artifacts
        run: vercel deploy --prebuilt --token=${{ env.VERCEL_TOKEN }}
        working-directory: site-repo
