name: Vercel Production Deployment

on:
  workflow_run:
    workflows: ["Build and Test"]
    types:
      - completed

env:
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  VERCEL_ORG_ID: ${{ secrets[format('{0}_VERCEL_ORG_ID', github.event.workflow_run.repository.name)] }}
  VERCEL_PROJECT_ID: ${{ secrets[format('{0}_VERCEL_PROJECT_ID', github.event.workflow_run.repository.name)] }}

jobs:
  deploy-production:
    if: |
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.event.workflow_run.head_repository.full_name }}
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: main

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Pull Vercel Production Environment
        run: |
          vercel pull --yes \
            --environment=production \
            --token=${{ env.VERCEL_TOKEN }} \
            --scope=${{ env.VERCEL_ORG_ID }}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ env.VERCEL_TOKEN }}

      - name: Deploy Production Artifacts
        run: vercel deploy --prebuilt --prod --token=${{ env.VERCEL_TOKEN }}
