name: Detect Project Type

on:
  workflow_call:
    inputs:
      repo_path:
        required: true
        type: string
    outputs:
      project_type:
        description: "Detected project type"
        value: ${{ jobs.detect-project-type.outputs.project_type }}

jobs:
  detect-project-type:
    runs-on: ubuntu-latest
    outputs:
      project_type: ${{ steps.detect.outputs.PROJECT_TYPE }}

    steps:
      - name: Use Existing Checkout Directory
        run: |
          echo "Using checked out repository at ${{ inputs.repo_path }}"
          ls -la ${{ inputs.repo_path }}

      - name: Detect `.cicd-config.yml`
        id: detect
        run: |
          PROJECT_TYPE="static"
          if [ -f "${{ inputs.repo_path }}/.cicd-config.yml" ]; then
            PROJECT_TYPE=$(grep "project_type:" ${{ inputs.repo_path }}/.cicd-config.yml | awk '{print $2}')
          fi
          echo "::set-output name=PROJECT_TYPE::$PROJECT_TYPE"
